# Site settings
title: Homing on Code
email: mulander@tintagel.pl
description: > # this means to ignore newlines until "baseurl:"
  Writing about OpenBSD, programming and anything else that grinds my gears
  that day.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.tintagel.pl" # the base hostname & protocol for your site
twitter_username: mulander
github_username:  mulander

# Build settings
markdown: kramdown
